### PR TITLE
Add inheritance for hooks

### PR DESCRIPTION
**Pull request by vsh91**
Hey, 

First off, thank you for gem.
This pull request is going to fix the bug with hooks inheritance #114   

Best,
Viktor

### CODE REVIEW

**Comment by kartikluke** [comment]
+1

**Comment by m20io** [comment]
👍

**Comment by kartikluke** [comment]
@laserlemon Could this be merged in. Would make the Interactor classes more intuitive.

**Comment by laserlemon** [comment]
Could you please try to add some tests that assert that hooks added to the child class are _not_ also added to the parent? Also, the implementation is a little verbose. Isn't there some cool `@@` class variable or `cattr_accessor` trick that's perfect for this sort of thing?

**Comment by babelian** [comment]
@laserlemon looks like @vsh91 added those specs, could this be merged (and version bumped) i'm using interactor in a gemspec and can only link to a rubygem (have been using github/ref in the Gemfile but that's no longer possible).

many thanks.

**Comment by arpitchauhan** [comment]
I think we should add hooks belonging to all ancestors (in proper order), not just those that belong to the (immediate) superclass. Ancestors also include the modules that a class has included, btw.

**Comment by povilasjurcys** [comment]
hey @arpitchauhan . I added extra tests for "deep inheritance" case and it seems that it works: https://github.com/vsh91/interactor/pull/1 Can you provide any example where this approach fails?

**Comment by povilasjurcys** [comment]
@laserlemon this PR is opened for almost 2 years. Can we merge this feature?

**Comment by matiasgarcia** [comment]
@laserlemon please merge this :)

**Comment by badBlackShark** [comment]
What's the holdup in merging this? This has been open for over **five and a half years** and is currently causing issues for the project I'm working on.

**Comment by vsh91** [comment]
https://github.com/collectiveidea/interactor/pull/191

**Pull request closed without merging**
